remote_theme: pages-themes/hacker@v0.2.0
title: Neels Notes

plugins:
  - jekyll-remote-theme 

# --- 1. DEFINE YOUR 'PATHS' COLLECTION ---
collections:
  paths:
    output: true 
    permalink: /paths/:name/ 


  boxes:
    output: true 
    permalink: /boxes/:name/ 

header_pages:
  - index.md
  - paths.md       # Link to the main Paths Index page
  - boxes.md       # Link to the main Boxes Index page
