remote_theme: pages-themes/hacker@v0.2.0
title: Neels Notes
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
 

header_pages:
  - index.md
  - htb-academy/index.md
  - boxes.md

